site_name: SQLModel BaseCRUD
repo_url: https://github.com/woofz/sqlmodel-basecrud
repo_name: woofz/sqlmodel-basecrud
edit_uri: ""
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - toc.integrate
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/github-alt

extra:
    version:
      provider: mike
      default: latest

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false